source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VersionsTracker_Example' do
    pod 'VersionsTracker', :path => '../'
end

target 'VersionsTracker_Tests' do
    pod 'VersionsTracker', :path => '../'

    pod 'Quick', git: 'https://github.com/Quick/Quick.git', branch: 'swift-3.0'
    pod 'Nimble', git: 'https://github.com/martnst/Nimble.git', branch: 'swift3'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
